apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 2
  template:
    metadata: 
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: niklasod/testapp:1.0
          ports:
            - containerPort: 8080